name: Jest
on: push
jobs:
    test:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@v4
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "24"

            - name: Install dependencies
              run: npm ci

            - name: Run tests
              run: npm test
