name: Check package
on: push
jobs:
    package:
        runs-on: ubuntu-26.04
        steps:
            - uses: actions/checkout@v6
            - name: Setup Node.js
              uses: actions/setup-node@v6
              with:
                  node-version: "24"

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build

            - name: Check package exports and types
              run: npm run check:package
